package com.java.fullstack2;

public class Exc0 {
	static void devide() {
		int d=0;
		int a=42/d;
	}

	public static void main(String[] args) {
		int d,a;
		devide();
		/*try {
			d=10;
			a=42/d;
			System.out.println("line no 14 will not execute");
		}catch(ArithmeticException ex) {
			System.out.println("Division by zero");
		}
		finally {
			System.out.println("after the catch block and inside finally block");
		}*/
	

	}

}
